#! /usr/bin/env python3

"""
Problem 2: Even Fibonacci Numbers
=================================

Link: https://projecteuler.net/problem=2

Description
===========

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

from pelib import generate_fibonacci_sequence

def solve() -> int:
    sum_of_even_terms = 0
    for fib in generate_fibonacci_sequence():
        if fib > 4000000:
            break
        if fib % 2 == 0:
            sum_of_even_terms += fib
    return sum_of_even_terms

def main():
    solution = solve()
    print("solution:", solution)

if __name__ == "__main__":
    main()
