#! /usr/bin/env python3

"""
Problem 12: Highly Divisible Triangle Number
============================================

Link: https://projecteuler.net/problem=12

Description
===========

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from pelib import factorize, generate_triangle_numbers

def divisor_count(n: int) ->int:
    assert n >= 1
    r = 1
    for (p, e) in factorize(n):
        r *= (e + 1)
    return r

def main():
    for t in generate_triangle_numbers():
        if (divisor_count(t)) > 500:
            break
    print("solution:", t)

if __name__ == "__main__":
    main()
