#! /usr/bin/env python3

"""
Problem 12: Highly Divisible Triangle Number
============================================

Link: https://projecteuler.net/problem=12

Description
===========

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

    1: 1
    3: 1, 3
    6: 1, 2, 3, 6
    10: 1, 2, 5, 10
    15: 1, 3, 5, 15
    21: 1, 3, 7, 21
    28: 1, 2, 4, 7, 14, 28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

def factorize(n: int) -> list[tuple[int, int]]:
    """Returns the factorization of the argument as a list of (prime, exponent) pairs."""
    assert n >= 1
    factors = []
    p = 2
    while p * p <= n:
        e = 0
        while n % p == 0:
            e += 1
            n //= p
        if e != 0:
            factors.append((p, e))
        p += 1
    if n != 1:
        factors.append((n, 1))
    return factors

def divisor_count(n: int) ->int:
    assert n >= 1
    r = 1
    for (p, e) in factorize(n):
        r *= (e + 1)
    return r

def main():
    tr = 1
    tri = 2
    while True:
        if divisor_count(tr) > 500:
            break
        tr += tri
        tri += 1
    print("solution:", tr)

if __name__ == "__main__":
    main()
